In [2]:
from ultralytics import YOLO

model = YOLO('yolo26n.pt')

# COCO8 예제 데이터셋으로 100 에포크 동안 모델 학습
results = model.train(data="coco8.yaml", epochs=100, imgsz=640)

Ultralytics 8.4.48  Python-3.11.9 torch-2.11.0+cpu CPU (Intel Core Ultra 7 255H)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco8.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train-5, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, p

In [3]:
from ultralytics import YOLO

model = YOLO('runs/detect/train-5/weights/best.pt')
metrics = model.val()

Ultralytics 8.4.48  Python-3.11.9 torch-2.11.0+cpu CPU (Intel Core Ultra 7 255H)
YOLO26n summary (fused): 122 layers, 2,408,932 parameters, 0 gradients, 5.4 GFLOPs
val: Fast image access  (ping: 0.00.0 ms, read: 838.8411.5 MB/s, size: 54.0 KB)
val: Scanning C:\Data\computer_vision\YOLO3\datasets\coco8\labels\val.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.7it/s 0.2s
                   all          4         17      0.906      0.646      0.887        0.7
                person          3         10          1      0.378      0.802      0.417
                   dog          1          1      0.794          1      0.995      0.895
                 horse          1          2       0.86          1      0.995      0.795
              elephant          1          2       0.78        0.5      0.543      0.302
              umbrella          1          

In [4]:
metrics.box.map

np.float64(0.6999857422632481)

In [5]:
metrics.box.map50

np.float64(0.8874326319675157)

In [6]:
metrics.box.map75

np.float64(0.821875)

In [7]:
metrics.box.maps

array([    0.41665,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,      0.8955,       0.795,     0.69999,     0.69999,     0.30176,     0.69999,     0.69999,     0.69999,
           0.69999,      0.8955,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,
           0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,      0.8955,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,     0.69999,
           0.69999,     0.69999,     0.6999

In [8]:
metrics.box.image_metrics

{'000000000042.jpg': {'precision': 0.00625,
  'recall': 1.0,
  'f1': 0.012422360248447204,
  'tp': 1,
  'fp': 159,
  'fn': 0},
 '000000000061.jpg': {'precision': 0.029411764705882353,
  'recall': 1.0,
  'f1': 0.05714285714285715,
  'tp': 5,
  'fp': 165,
  'fn': 0},
 '000000000049.jpg': {'precision': 0.042328042328042326,
  'recall': 0.8888888888888888,
  'f1': 0.0808080808080808,
  'tp': 8,
  'fp': 181,
  'fn': 1},
 '000000000036.jpg': {'precision': 0.08333333333333333,
  'recall': 1.0,
  'f1': 0.15384615384615385,
  'tp': 2,
  'fp': 22,
  'fn': 0}}

In [9]:
model.save('yolo26n-detect.pt')

In [10]:
detect_model = YOLO('yolo26n-detect.pt')

In [11]:
results = detect_model.predict('bus.jpg')


image 1/1 c:\Data\computer_vision\YOLO3\bus.jpg: 640x480 4 persons, 1 bus, 73.0ms
Speed: 3.0ms preprocess, 73.0ms inference, 0.3ms postprocess per image at shape (1, 3, 640, 480)


In [12]:
for result in results:
    names = [result.names[cls.item()] for cls in result.boxes.cls]
    confs = result.boxes.conf

In [13]:
names

['person', 'person', 'bus', 'person', 'person']

In [14]:
confs

tensor([0.9420, 0.9231, 0.9168, 0.9090, 0.7903])

In [15]:
results = detect_model.predict("bird.jpg")


image 1/1 c:\Data\computer_vision\YOLO3\bird.jpg: 480x640 1 bird, 84.5ms
Speed: 2.2ms preprocess, 84.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)


In [16]:
for result in results:
    names = [result.names[cls.item()] for cls in result.boxes.cls]
    confs = result.boxes.conf

In [17]:
confs

tensor([0.9327])

In [18]:
names

['bird']